# -*- coding: iso-8859-15 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: pyreguiTests.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Window functions

ID_STATICBITMAP = 10000
ID_GRID = 10001

def MyDialogFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item1 = wx.StaticBitmap( parent, ID_STATICBITMAP, MyBitmapsFunc( 0 ), wx.DefaultPosition, wx.DefaultSize )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item2 = wx.grid.Grid( parent, ID_GRID, wx.DefaultPosition, [300,160], wx.WANTS_CHARS )
    item2.CreateGrid( 10, 10, wx.grid.Grid.SelectCells )
    item0.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


def MyBitmapsFunc( index ):
    if index == 0:
        return wx.Image( "pyreguiTests_wdr/MyBitmapsFunc_0.png", wx.BITMAP_TYPE_PNG ).ConvertToBitmap()
    return wx.NullBitmap

# End of generated file
